import { GoogleGenAI, Modality } from "@google/genai";
import { PersonaDNA, SceneDetails } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateInfluencerImage(images: { data: string; mimeType: string }[], prompt: string): Promise<string> {
    
    const imageParts = images.map(image => ({
        inlineData: {
            data: image.data,
            mimeType: image.mimeType,
        },
    }));

    const allParts = [...imageParts, { text: prompt }];

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: allParts,
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated by the API.");
}

export async function generateCaption(persona: PersonaDNA, scene: SceneDetails): Promise<string> {
    const prompt = `
        You are an AI influencer caption writer. Your goal is to create short, emotional, and authentic captions that feel human.
        
        Influencer Profile:
        - Personality: ${persona.personality}
        - Aesthetic: ${persona.aesthetic}
        
        Scene Details:
        - Location: ${scene.location}
        - Time: ${scene.time}
        - Mood: ${scene.mood}
        - Activity: ${scene.activity}
        
        Generate a caption for an image depicting this scene. The caption should be in lowercase, feel introspective and candid.
        Add 2-3 minimal, aesthetic, mood-based hashtags.
        
        Example Output:
        i've stopped chasing perfect days.
        somehow, they find me when i stop trying.
        🌿 #reallifevibes #quietconfidence #aiinfluencer

        Now, write a new one for the provided scene.
    `;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
    });
    
    return response.text.trim();
}